CREATE TABLE `MyTwitter`.`Tweet` ( `id` INT NOT NULL AUTO_INCREMENT , `userId` INT NOT NULL , `text` VARCHAR(140) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL , `creationDate` DATETIME NOT NULL, 
PRIMARY KEY (`id`),
CONSTRAINT fk_1 
FOREIGN KEY (`userId`) REFERENCES User(`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE = InnoDB;

CREATE TABLE `MyTwitter`.`Comment` ( `id` INT NOT NULL AUTO_INCREMENT , `userId` INT NOT NULL , `postId` INT NOT NULL , `creationDate` DATETIME NOT NULL , `text` VARCHAR(60) NOT NULL , 
PRIMARY KEY (`id`), 
CONSTRAINT fk_2 
FOREIGN KEY (`userId`) REFERENCES User(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (`postId`) REFERENCES Tweet(`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE = InnoDB;

CREATE TABLE `MyTwitter`.`Message` ( `id` INT NOT NULL AUTO_INCREMENT , `text` VARCHAR(60) NOT NULL , `date` DATETIME NOT NULL , `sender` INT NOT NULL , `receiver` INT NOT NULL , 
PRIMARY KEY (`id`)) ENGINE = InnoDB;

ALTER TABLE `Message` ADD 
FOREIGN KEY (`sender`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `Message` ADD 
FOREIGN KEY (`receiver`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Message` ADD `ifRead` INT NOT NULL AFTER `receiver`;